import type { Metadata } from "next";
import {
  Cabin,
  Geist,
  Geist_Mono,
  Lora,
  Monsieur_La_Doulaise,
  Mulish,
  Poppins,
  Quicksand,
  Roboto,
} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import { Suspense } from "react";
import Loading from "./loading";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const mulish = Mulish({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-mulish",
});

const lora = Lora({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-lora",
});

const cabin = Cabin({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-cabin",
});

const quicksand = Quicksand({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-quicksand",
});

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-roboto",
});
const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-poppins",
});

const monsieur_la_doulaise = Monsieur_La_Doulaise({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-Monsieur_La_Doulaise",
});

export const metadata: Metadata = {
  title: "Biz Bize",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${mulish.variable} ${lora.variable} ${cabin.variable} ${quicksand.variable} ${roboto.variable} ${poppins.variable} ${monsieur_la_doulaise.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Suspense fallback={<Loading />}>
            {children}
          </Suspense>
        </ThemeProvider>
      </body>
    </html>
  );
}
